config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'jobs#index'

  resources :jobs

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
  	find_or_create_by(uid :auth.uid, provider: auth.provider)
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
	before_save :query_link
	belongs_to :user
	require 'net/http'

	def query_link
		uri = URI(self.url)
		res = Net::HTTP.get_response(uri)
		return res.code
	end

	def res_display(code)
		if code == "200"
			return "Active Job"
		elsif code == "404"
			return "Inactive Job"
		else
			return "Unknown Status"
		end
	end

	def applied?
		self.apply ? "Yes" : "No"
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs

  def self.connect_to_linkedin(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else

        user = User.create(name:auth.info.first_name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
before_action :authenticate_user!

	def index
		@jobs = current_user.jobs
	end

	def new
		@job = Job.new
	end

	def create
		@job = current_user.jobs.build(job_params)
		# @job = Job.new(job_params)
		# @job.user = current_user
		@job.save
		redirect_to jobs_path
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])

		if @job.update(job_params)
			redirect_to jobs_path
		else
			render 'edit'
		end
	end

	def destroy
		@job = Job.find(params[:id])
		@job.destroy

		redirect_to jobs_path
	end

	private
		def job_params
			params.require(:job).permit(:company, :title, :url, :apply)
		end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
	def linkedin
    auth = env["omniauth.auth"]
    @user = User.connect_to_linkedin(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.linkedin_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
  	end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Jobs/_form.html.erb
<%= form_for @job do |job| %>
	<p>
		<%= job.label :Company %><br>
		<%= job.text_field :company %>
	</p>

	<p>
		<%= job.label :Title %><br>
		<%= job.text_field :title %>
	</p>

	<p>
		<%= job.label :URL %><br>
		<%= job.text_field :url %>
	</p>

	<p>
		<%= job.label :Applied? %><br />
		<%= job.check_box :apply %>
	</p>

	<p>
		<%= job.submit %>
	</p>
<% end %>

app/views/Jobs/edit.html.erb
<h1>Edit Job Information</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/Jobs/index.html.erb
<h1>Application Tracker</h1>

</br>

<%= link_to 'Track New Job', new_job_path, class: 'btn btn-default' %>

<table class="flat-table flat-table-1">
	<tr>
		<th>Company</th>
		<th>Title</th>
		<th>Job Description URL</th>
		<th>Job Status</th>
		<th>Applied?</th>
		<th>Edit</th>
	</tr>

<% @jobs.each do |job| %>
			<tr>
				<td><%= job.company %></td>
				<td><%= job.title %></td>
				<td><%= link_to job.url, job.url %></td>
				<td><%= job.res_display(job.query_link) %></td>
				<td><%= job.applied? %></td>
				<td><%= link_to 'Edit', edit_job_path(job) %> | <%= link_to 'Delete Job', job_path(job), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
</table>

app/views/Jobs/new.html.erb
<h2>Track a New Job</h2>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>

  	 <% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path,:method => :delete %>

		<% end %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>